path_to_data: 'data/raw/heart_cleveland_upload.csv'
path_to_metrics: 'models/metrics/metrics_lr.json'
path_to_model: 'models/model_lr.pkl'

train_params:
    model_type: 'LogisticRegression'
    grid_search: True

splitting_params:
  val_size: 0.2
  random_state: 17

feature_params:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  target_column: 'condition'



